site_name: Steal These Ideas
site_url: https://oenig138.github.io/STI/

theme:
  name: material
  palette:
    scheme: slate  # Default to dark mode
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
      

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - toc:
      permalink: true

extra_css:
  - assets/cards.css

nav:
  - Home: index.md
  - Character Concepts:
      - Alveta "Velvet": character_concepts/alveta-velvet.md
      - Aramis Rosarian: character_concepts/aramis-rosarian.md
      - Beitian "Betty" Winters Heart: character_concepts/beitian-winters-heart.md
      - Belvarax "Gobsmack" Allimander: character_concepts/belvarax-allimander.md
      - Calypso "So-So" Sonder: character_concepts/calypso-so-so-sonder.md
      - Cephala Fortina: character_concepts/cephala-fortina.md
      - Clover Medley: character_concepts/clover-medley.md
      - Donner: character_concepts/donner.md
      - Felmin Dilthey: character_concepts/felmin-dilthey.md
      - Geldok Iron Tusk: character_concepts/geldok-iron-tusk.md
      - Harold Carnap: character_concepts/harold-carnap.md
      - Korak the Gilded: character_concepts/korak-the-gilded.md
      - Lia Amberhorn: character_concepts/lia-amberhorn.md
      - Rikiki Twilk: character_concepts/rikiki-twilk.md
      - Simeon Blackreef: character_concepts/simeon-blackreef.md
      - Thimble: character_concepts/thimble.md
      - Tippy: character_concepts/tippy.md
      - Yawp Cumuluni: character_concepts/yawp-cumuluni.md
      - Yelena Gagarina: character_concepts/yelena-gagarina.md
  - Locations:
      - Lith and Flesh: locations/the-lith-and-flesh.md